project_id = "mpjqrijapdptceptkhje"
VITE_SUPABASE_PROJECT_ID="mpjqrijapdptceptkhje"
VITE_SUPABASE_PUBLISHABLE_KEY="sb_publishable_qd_tkaoTomw9A65maAuPQw_P0o2UKMd"
VITE_SUPABASE_URL="https://mpjqrijapdptceptkhje.supabase.co"